# legs by order of aqcuisition: [weight, poise]
# 11.03.2022

legs = {}

legs["-naked-"] = [0, 0]
legs["Astrologer Trouser"] = [3.9, 3]
legs["Foot Soldier Greaves"] = [5.1, 4]
legs["Traveler's Slops"] = [2.5, 1]
legs["Cloth Trousers"] = [2, 1]
legs["Godrick Soldier Greaves"] = [6.6, 10]
legs["Warrior Greaves"] = [4.8, 4]
legs["Sorcerer Leggings"] = [2, 1]
legs["Royal Remains Greaves"] = [6.6, 9]
legs["Prisoner Trousers"] = [2, 1]
legs["Vulgar Militia Greaves"] = [5.1, 4]
legs["Fur Leggings"] = [3.1, 1]
legs["Cuckoo Knight Greaves"] = [7.3, 11]
legs["Finger Maiden Shoes"] = [2.5, 1]
legs["Redmane Knight Greaves"] = [7.3, 11]
legs["Radahn Soldier Greaves"] = [6.6, 10]
legs["Radahn's Greaves"] = [10.8, 17]
legs["Queen's Leggings"] = [2, 1]
legs["Mausoleum Knight Greaves"] = [7.3, 12]
legs["Nox Monk Greaves"] = [5.1, 4]
legs["Shaman Leggings"] = [3.1, 1]
legs["Godskin Noble Trousers"] = [2.5, 1]
legs["Snow Witch Skirt"] = [3.1, 1]
legs["Preceptor's Trousers"] = [3.9, 2]
legs["Depraved Perfumer Trousers"] = [4.3, 2]
legs["Spellbade's Trousers"] = [2.6, 1]
legs["Aristocrat Boots"] = [2.9, 1]
legs["Scaled Greaves"] = [9.9, 16]
legs["Bull-Goat Greaves"] = [16.4, 28]
legs["Omenkiller Boots"] = [4.4, 4]
legs["Twinned Greaves"] = [7.3, 10]
legs["Crucible Greaves"] = [9.6, 16]
legs["Noble's Trousers"] = [3.9, 1]
legs["Battlemage Legswraps"] = [2.5, 1]
legs["Pagee Trousers"] = [2.5, 1]
legs["Confessor Boots"] = [4.8, 3]
legs["Guardian Greaves"] = [5.5, 3]
legs["Land of Reeds Greaves"] = [5.1, 4]
legs["Blaidd's Greaves"] = [8.5, 14]
legs["Briar Greaves"] = [7.3, 9]
legs["Mushroom Legs"] = [3.1, 1]
legs["Eccentric's Breeches"] = [5.1, 6]
